### ISSUE TITLE
Regression: Unable to run an old banner table

### ISSUE THREAD

**Issue by weswil07** [mediapredict/daffodil#130]
[Seen in [logs](https://mediapredict.sentry.io/issues/5322607425/events/13823b28b1bf4ed693178b69b2d258ff/?project=8836) and reported by [Marla](https://mediapredict.slack.com/archives/C03T657JJ/p1715202487582859)]

The error is encountered when running [this table](https://knittingfactory.herokuapp.com/admin/explorer/table/95/change/?_changelist_filters=q%3Dbenchmark).

I'm able to run the table locally on a version of KF that is up to date prior to the latest daffodil changes (May 1). The database is a little behind too, so there could be some new data causing the issue.

**Comment by igorkramaric** [comment]
Turned out this happened due to a badly formatted daffodil, so closing
