### ISSUE TITLE
Add syntactic sugar for datetime values

### ISSUE THREAD

**Issue by jiaaro** [mediapredict/daffodil#47]
In Daffodil we generally store timestamps as unix time (i.e., seconds since Jan 1, 1970) so if you wanted to target users who participated in a study between Aug 3 and Aug 5 2017 you'd write:

```
duracell_copy_main__started > 1501743600
duracell_copy_main__started < 1501916400
```

Aug 3, 2017 == `1501743600` == `datetime(2017, 8, 3).timestamp()`

ideally we'd allow analysts to write:

```
duracell_copy_main__started >= timestamp(2017-08-03)
```

which, the `timestamp(…)` portion would be converted to the appropriate float value during daffodil compilation

**Comment by ajabdelaziz** [comment]
#48
