### ISSUE TITLE
Pip 20 build problems

### ISSUE THREAD

**Issue by igorkramaric** [mediapredict/daffodil#70]
With Pip 20 Daffodil gets built in a strange way, so importing it's main class doesn't work. As seen here:

```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/dpm/apps/dpm_core/models.py", line 26, in <module>
    from daffodil import Daffodil
ImportError: cannot import name 'Daffodil' from 'daffodil' (unknown location)
```

This is easily reproducible  on a local machine.

Until this issue is solved, for Heroku deployments (including tests), an immediate cure is previous buildpack version in the app.json, which is `https://github.com/heroku/heroku-buildpack-python#v163`

**Comment by igorkramaric** [comment]
It seems that many people were hit by the same problem: https://github.com/pypa/pip/issues/7620

Probably we should do nothing until solution is found for buildpack

**Comment by igorkramaric** [comment]
status

pip 20.2.3. does the job, but it's still not used by the latest `heroku-buildpack-python`

heroku-buildpack-python still uses old 20.1.1 pip version [as seen](https://github.com/heroku/heroku-buildpack-python/blob/main/test/run-versions#L12) in the buildpack tests

**Comment by tedsmoore** [comment]
I can verify this worked for me locally. Required `pip uninstall daffodil` and I used the `--no-cache-dir` option when installing (though it might have worked without it), but just documenting the steps here in the event we come across it again.

**Comment by igorkramaric** [comment]
@tedsmoore pip 20.2.3.? works without the cache switch too. Problem happens only on Heroku builds, because of the buildpack

**Comment by Schwarzschild** [comment]
Is there a question we should ask Heroku directly with a ticket?

**Comment by igorkramaric** [comment]
I don't think so. This doesn't regard the core Heroku machinery, it's about open source buildpack: https://github.com/heroku/heroku-buildpack-python
